dataset_root: "../../miniImagenet"
IMAGE_SIZE: 84
 
feature_extractor_type: "Conv4" # options: "Conv4", "ResNet"
metric_type: "TCA"    # options: "RN", "TCA", "resRN","resTCA"

pretrained: True
finetune: True

display_freq: 200
val_freq: 2000

gpu: 0
num_workers: 3
n_way: 5
n_shot: 5
n_query_train: 10
n_query_test: 10
# feature_dim: 64 # Conv4:64, ResNet:640
n_episode_each_epoch: 2000
test_episode: 600
lr: 0.001
loss_type: "mse"
optimizer: "Adam"
weight_decay: 0 

